version: '3.9'

services:

  db:
    image: postgres:13.6
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: on-failure
    healthcheck:
      test: "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'select 1;'"
      interval: 1s
      retries: 20
    volumes:
      - database_niste_postari_dev:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - niste_postari_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5
    networks:
      - niste_postari_dev
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      retries: 20
    ports:
      - "6379:6379"

volumes:
  database_niste_postari_dev:

networks:
  niste_postari_dev:
